/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -t bad_clientele_logo.gltf
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body1: THREE.Mesh
  }
  materials: {
    ['Leather - Weathered']: THREE.MeshStandardMaterial
  }
}

export function BadClientele(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/bad_clientele_logo.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[8, -30, 0]} rotation={[0, 0, Math.PI / 2]} scale={0.03}>
        <mesh geometry={nodes.Body1.geometry} material={materials['Leather - Weathered']} rotation={[2.84, Math.PI / 2, 0]} scale={10} />
      </group>
      <pointLight intensity={1} decay={2} color="#fcfcfc" position={[-12.44, 12.49, 15.73]} />
    </group>
  )
}

useGLTF.preload('/bad_clientele_logo.gltf')
