/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bad_clientele_logo.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BadClientele(props:any) {
  const { nodes, materials } = useGLTF('/bad_clientele_logo.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 4.75, 0]} rotation={[0, 0, Math.PI / 2]} scale={0.1}>
        <mesh geometry={nodes.Body1.geometry} material={materials['Leather - Weathered']} rotation={[2.84, Math.PI / 2, 0]} scale={10} />
      </group>
      <pointLight intensity={1} decay={2} color="#fcfcfc" position={[-12.44, 12.49, 15.73]} />
    </group>
  )
}

useGLTF.preload('/bad_clientele_logo.gltf')
