/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 buckling_spring.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BucklingSpring(props:any) {
  const { nodes, materials } = useGLTF('/buckling_spring.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.5}>
        <mesh geometry={nodes.Adapter.geometry} material={materials['Plastic - Translucent Matte (White)']} position={[-3.19, 8.82, -4.56]} rotation={[-1.13, 0, 0]} scale={10} />
      </group>
      <pointLight intensity={1} decay={2} color="#fcfcfc" position={[-12.44, 12.49, 15.73]} />
    </group>
  )
}

useGLTF.preload('/buckling_spring.gltf')
