/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -t keyboard_mounts.gltf
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body1: THREE.Mesh
  }
  materials: {
    ['Rilsan Invent Natural - PA 11']: THREE.MeshStandardMaterial
  }
}

export function KeyboardMounts(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/keyboard_mounts.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[8,-15,0]} scale={0.02}>
        <mesh geometry={nodes.Body1.geometry} material={materials['Rilsan Invent Natural - PA 11']} position={[61.18, -87.36, -105.64]} rotation={[-1.31, -0.5, -1.8]} scale={10} />
      </group>
    </group>
  )
}

useGLTF.preload('/keyboard_mounts.gltf')
