/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 long_lines_necklace.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LongLines(props:any) {
  const { nodes, materials } = useGLTF('/long_lines_necklace.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[5.54, 5.74, 0]} rotation={[-Math.PI / 2, -0.09, -Math.PI / 2]} scale={0.1}>
        <mesh geometry={nodes.Body8.geometry} material={materials['Aluminum - Polished']} scale={10} />
        <mesh geometry={nodes.Body16.geometry} material={materials['Aluminum - Polished']} scale={10} />
      </group>
      <pointLight intensity={1} decay={2} color="#fcfcfc" position={[-12.44, 12.49, 15.73]} />
    </group>
  )
}

useGLTF.preload('/long_lines_necklace.gltf')
