/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 slavboard.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Slavboard(props:any) {
  const { nodes, materials } = useGLTF('/slavboard.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[15.51, 0, -16.98]} rotation={[-0.44, 0.44, Math.PI / 2]} scale={0.1}>
        <mesh geometry={nodes.Body1_4.geometry} material={nodes.Body1_4.material} />
        <mesh geometry={nodes.Body1_5.geometry} material={nodes.Body1_5.material} />
        <mesh geometry={nodes.Body1_6.geometry} material={nodes.Body1_6.material} />
        <mesh geometry={nodes.Body2_3.geometry} material={nodes.Body2_3.material} />
        <mesh geometry={nodes.Body2_4.geometry} material={nodes.Body2_4.material} />
        <mesh geometry={nodes.Body2_5.geometry} material={nodes.Body2_5.material} />
        <mesh geometry={nodes.Body3_1.geometry} material={nodes.Body3_1.material} />
        <mesh geometry={nodes.Body4_2.geometry} material={nodes.Body4_2.material} />
        <mesh geometry={nodes.Body4_3.geometry} material={nodes.Body4_3.material} />
        <mesh geometry={nodes.Body5_2.geometry} material={nodes.Body5_2.material} />
        <mesh geometry={nodes.Body5_3.geometry} material={nodes.Body5_3.material} />
      </group>
      <pointLight intensity={1} decay={2} color="#fcfcfc" position={[-12.44, 12.49, 15.73]} />
    </group>
  )
}

useGLTF.preload('/slavboard.gltf')
